<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>


<textarea class="form-control" readonly="readonly" style="height: 200px;">
...............
...............
...............
...............
...............
...............
</textarea>